### ISSUE TITLE
Slow request

### ISSUE THREAD

**Issue by ludovic-pl** [cleishm/libneo4j-client#27] opened 2018-06-21 08:49 UTC
Hello,
I have some strange behaviour with the library. The execution time of a simple request such as
`MATCH (n:NODE_LABEL) RETURN count(n)`
is super fast using the browser console but when using libneo4j client the request is taking forever.
I tried the same command using the python official package and it is as fast as the browser command.

Where do you think is the bottleneck in the library ?

**Comment by cleishm** [comment] 2018-06-21 14:39
Hi @ludovic-pl!

I suspect it’s not a problem in the library, as that specific query would be sent as a whole and returns only a single value. There’s not much for the library to do.

Let’s confirm that though. Can you run the query again using `-vvv`, which will enable trace logging, and send the output?

Chris

**Comment by cleishm** [comment] 2018-06-21 14:45
Use:

```
echo "MATCH (n:NODE_LABEL) RETURN count(n)" | \
        neo4j-client -vvv -u neo4j -P localhost
```

Or similar.

**Comment by ludovic-pl** [comment] 2018-06-21 16:21
Hello @cleishm ,
I run your command as you ask and there is the output:
`
DEBUG [connection]: attempting connection to 172.31.3.28 [7687]
TRACE [connection]: opened socket to 172.31.3.28 [7687] (fd=4)
TRACE [connection]: initialiting TLS (fd=4)
DEBUG [tls]: server cert fingerprint: 0d1dc9cab6b5d554eab5c41449dcc793f067d930a48ea7a09dace4a83359d28a223eed4fa1111f40637224a0f424a5fb42e9d27ce5c47f7821bbc9cfff7271c8
DEBUG [tls]: TLS certificate verification failed: self signed certificate
INFO  [connection]: connected (0x56115bf96350) to 172.31.3.28:7687
DEBUG [connection]: connection 0x56115bf96350 using protocol version 1
Password: 
TRACE [connection]: enqu INIT{"libneo4j-client/2.2.0", {scheme: basic, principal: "neo4j", credentials: ****}} (0x56115bf96bc0) in 0x56115bf96350
DEBUG [connection]: sent INIT (0x56115bf96bc0) in 0x56115bf96350
DEBUG [connection]: rcvd SUCCESS in response to INIT (0x56115bf96bc0)
TRACE [connection]: SUCCESS in 0x56115bf96350 (response to INIT): {server:"Neo4j/3.4.0"}
TRACE [connection]: enqu RUN{"MATCH (n:Entry) RETURN count(n)
", {}} (0x56115bf96ca0) in 0x56115bf96350
TRACE [connection]: enqu PULL_ALL (0x56115bf96d80) in 0x56115bf96350
DEBUG [connection]: sent RUN (0x56115bf96ca0) in 0x56115bf96350
DEBUG [connection]: sent PULL_ALL (0x56115bf96d80) in 0x56115bf96350
DEBUG [connection]: rcvd SUCCESS in response to RUN (0x56115bf96ca0)
TRACE [results]: SUCCESS in 0x56115bf96350 (response to RUN): {result_available_after:0,fields:["count(n)"]}
"count(n)"
DEBUG [connection]: rcvd RECORD in response to PULL_ALL (0x56115bf96d80)
28052
DEBUG [connection]: rcvd SUCCESS in response to PULL_ALL (0x56115bf96d80)
TRACE [results]: SUCCESS in 0x56115bf96350 (response to PULL_ALL): {result_consumed_after:0,type:"r"}
INFO  [connection]: disconnected 0x56115bf96350
`

When i run the command as you ask, the request end nearly instantly, but when i run it interactively, it take forever.

**Comment by ludovic-pl** [comment] 2018-07-03 09:16
Hello @cleishm sorry to bother you with this issue, but do you have some idea on how i can help you to resolve this problem ?
When I use the API in C++ I have also slow execution time. But when i try the same kind of request (same request with the same parameters) using the python API, i don't have this kind of slowness.

**Comment by cleishm** [comment] 2018-07-11 22:46
Hi @ludovic-pl! Any progress on building an environment (e.g. docker image?) where we can reproduce your issue?

**Comment by cleishm** [comment] 2018-11-06 13:48
I am unable to reproduce this issue, despite trying a few different things. I'm closing it now.

If you can reproduce the error in a way that can be replicated, I'll happily re-open it.

**Closed by cleishm** 2018-11-06 13:48 UTC
