### ISSUE TITLE
DateTime not working due to outdated Bolt Driver

### ISSUE THREAD

**Issue by seajaysec** [cleishm/libneo4j-client#46] opened 2019-10-14 21:19 UTC
When running queries that include [DateTime](https://neo4j.com/docs/cypher-manual/current/functions/temporal/datetime/) I receive the following error:
```
DateTime is not supported as a return type in Bolt protocol version 1. Please make sure driver supports at least protocol version 2. Driver upgrade is most likely required.
```

Would it be possible to add support for Bolt version 2 to neo4j-client?

**Comment by cleishm** [comment] 2019-10-14 21:27
This is a duplicate of #36. I would love to see support for this added, and there has been some work toward that in the branch https://github.com/cleishm/libneo4j-client/tree/neo4j-proto-2.

Sadly, Neo4j has created new protocol versions of their own, and not published those. So it needs someone to reverse engineer these protocol changes.

**Closed** 2019-10-14 21:28 UTC
