### ISSUE TITLE
libtool:   error: 'libneo4j_client_la-client_config.lo' is not a valid libtool object

### ISSUE THREAD

**Issue by davisford** [cleishm/libneo4j-client#44] opened 2019-10-02 21:00 UTC
Trying to build on Debian, and have to do `make -i install` to get past compiler warnings as errors, but still fails with `libtool`:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -pthread -Wpedantic -Wvla -g -O2 -std=gnu11 -fvisibility=hidden -pipe -Wall -W -Werror -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wstrict-prototypes -Wcast-qual -Wcast-align -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -MT libneo4j_client_la-print.lo -MD -MP -MF .deps/libneo4j_client_la-print.Tpo -c print.c  -fPIC -DPIC -o .libs/libneo4j_client_la-print.o
print.c: In function 'neo4j_null_str':
print.c:52:9: error: 'strncpy' output may be truncated copying between 1 and 5 bytes from a string of length 4 [-Werror=stringop-truncation]
         strncpy(buf, "null", n);
         ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: [Makefile:679: libneo4j_client_la-print.lo] Error 1 (ignored)
mv -f .deps/libneo4j_client_la-print.Tpo .deps/libneo4j_client_la-print.Plo
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -pthread  -Wpedantic -Wvla -g -O2 -std=gnu11 -fvisibility=hidden -pipe -Wall -W -Werror     -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith     -Wstrict-prototypes -Wcast-qual -Wcast-align -Wno-error=unused-function     -Wno-error=unused-variable -Wno-error=deprecated-declarations -version-info 13:0:2  -o libneo4j-client.la -rpath /usr/local/lib libneo4j_client_la-error_handling.lo libneo4j_client_la-buffering_iostream.lo libneo4j_client_la-chunking_iostream.lo libneo4j_client_la-client_config.lo libneo4j_client_la-connection.lo libneo4j_client_la-deserialization.lo libneo4j_client_la-dotdir.lo libneo4j_client_la-init.lo libneo4j_client_la-iostream.lo libneo4j_client_la-logging.lo libneo4j_client_la-memory.lo libneo4j_client_la-messages.lo libneo4j_client_la-metadata.lo libneo4j_client_la-network.lo libneo4j_client_la-print.lo libneo4j_client_la-posix_iostream.lo libneo4j_client_la-render.lo libneo4j_client_la-render_plan.lo libneo4j_client_la-render_results.lo libneo4j_client_la-result_stream.lo libneo4j_client_la-ring_buffer.lo libneo4j_client_la-serialization.lo libneo4j_client_la-thread.lo libneo4j_client_la-tofu.lo libneo4j_client_la-u8.lo libneo4j_client_la-uri.lo libneo4j_client_la-util.lo libneo4j_client_la-values.lo libneo4j_client_la-openssl.lo libneo4j_client_la-openssl_iostream.lo  -lssl -lcrypto -lm 
libtool:   error: 'libneo4j_client_la-client_config.lo' is not a valid libtool object
make[3]: [Makefile:520: libneo4j-client.la] Error 1 (ignored)
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 neo4j-client.h '/usr/local/include'
make[3]: Leaving directory '/src/libneo4j-client-2.2.0/src/lib'
```

**Comment by davisford** [comment] 2019-10-02 21:01
[config.log](https://github.com/cleishm/libneo4j-client/files/3683322/config.log)

**Comment by cleishm** [comment] 2019-10-02 21:41
Duplicate of #38

**Closed by cleishm** 2019-10-02 21:41 UTC

**Comment by davisford** [comment] 2019-10-03 02:21
@cleishm I don't think that is a dupe?  He's getting string warnings -- I get the same warnings, but mine fails to compile if I use `make -i` to skip warnings.  Mine fails on `libtool`.

In any event, I'm building in a Docker container.  I was using `bitnami:minideb`, but I've instead gone with an Ubuntu derivative, and I was able to move past it.

Relevant Docker command for necessary deps:

```
RUN apt update && \
  apt -y --force-yes -o Dpkg::Options::="--force-confnew" upgrade && \
  apt-get install -q -y wget build-essential libssl-dev libncurses-dev pkg-config libtool openssl && \
  apt-get clean
```
